### ISSUE TITLE
Edit Task is not working

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TIK-TIK-App#30]
### Description of issue
Edit task not working

### Expected result
after editing the task. The task must be Edited.

### Actual result
After editing the task.The task is not editing.

### Steps to reproduce
1. sign in with credential
2. Click add task
3. add the task and click edit button and edit the task.

```
Path:      /dashboard
Browser:   Chrome 127.0.0.0 on Windows 10
Viewport:  1504 x 868 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-28--tiktik-trackerz.netlify.app%2Fdashboard&os=Windows&os_version=10&browser=Chrome&browser_version=127.0&resolution=1504x868&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #28](https://deploy-preview-28--tiktik-trackerz.netlify.app/dashboard)

**Comment by vigneshwarvj** [comment]
Working fine in current build (09 Aug). Check once.
